testing github actions

diff --git a/.github/workflows/repos.yml b/.github/workflows/repos.yml
--- a/.github/workflows/repos.yml
+++ b/.github/workflows/repos.yml
@@ -71,7 +71,12 @@ jobs:
       - name: Compare Repositories
         run: |
           for repo in ${{ steps.list_repos.outputs.result }}; do
-            if ! echo "${{ steps.extract_mapping.outputs.filtered_mapping }}" | grep -q "$repo"; then
-              echo "Repository $repo is missing from Intersphinx Mapping."
-            fi
+          # Remove single quotes from the filtered_mapping using sed
+          filtered_mapping_without_quotes=$(echo "${{ steps.extract_mapping.outputs.filtered_mapping }}" | sed "s/'//g")
+        
+          # Check if the repository exists in the filtered_mapping
+          if ! echo "$filtered_mapping_without_quotes" | grep -q "$repo"; then
+            echo "Repository $repo is missing from Intersphinx Mapping."
+          fi
           done
+    
